title: Christiana All Seasons Resort
author: Adrien de Pierres
description: Escape to tranquility and experience luxury, comfort and soulful dining.
telephone:
  main: +2761 463 3848
  alt: +2761 463 3138
  emergency: +2776 553 8955
email: bookings@casr.co.za
